/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models3d/character/bot.glb -o src/components3D/character/MyBot.jsx -r public 
Author: e-toma (https://sketchfab.com/e-toma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sketchbot-37c871cbd9174f67bda4c10d19a97ed0
Title: Sketchbot
*/

import  { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function MyBot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models3d/character/bot.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  return (
    <group ref={group} {...props} position={[-0.5,-0.2,-0.1]} scale={0.3}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ca242c97b9dd43a6bdc52916c4a7aa5bfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BOT" position={[0, 0, 0]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_7" position={[-4.995, -3.942, 3.68]} />
                    <group name="Object_9" position={[-1.665, -0.905, 1.227]} />
                    <group name="EYE" position={[-3.33, -3.037, 2.453]} />
                    <group name="Merged_A7_export" />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Nuovo} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Merged_A7_export} skeleton={nodes.Object_10.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models3d/character/bot.glb')
